### ISSUE TITLE
Production Checklist

### ISSUE THREAD

**Issue by cobusc** [girleffect/core-general#25]
# Task Descriptions

## Update master branch
Merge develop with master branch. Create a release tag and push.

## Image on dockerhub?
Check that the Docker image built for the "latest" tag as well as the release tag is available on [Dockerhub](http://hub.docker.com)

## Configure new deployment pipelines
Some services have multiple delployment pipelines, typically for the service itself and for running migrations. Clone these pipelines and set the account to the production account and reqion.

Use the "latest" tag to pull images from dockerhub.

Update the configuration to point to the newly created production supporting services(DB/Memcache/Redis).

Update the names of the following services to have the form "xxx.gehosting.org":
* Authentication Service: `auth.gehosting.org`
* Management Layer: `api.gehosting.org`
* Management Portal: `portal.gehosting.org`

The Access Control and User Data Store services technically should not be exposed to the outside world, so they do not need to use the "gehosting.org" domain, but can for now.

## Deploy to prod
Run the migration pipelines for services that has one configured.
Check that migrations succeeded using Sumlogic.
Run the deployment pipeline.
Check that the service deploys correctly.

## Change docker image used to a versioned one
Because we foresee some potential changes to some of the components (most notably Auth Service and Management Portal) we configure the containers to use use the "latest" tag when deploying to production. At a later stage we should change this to not pull the "latest", but rather a specific release tag.

# Component Deployment Status

## Authentication Service
- [ ] Update master branch
- [ ] Image on dockerhub?
- [ ] Configure new deployment pipelines
- [ ] Deploy to prod
- [ ] Change docker image used to a versioned one (later)

## Access Control
- [ ] Update master branch
- [ ] Image on dockerhub?
- [ ] Configure new deployment pipelines
- [ ] Deploy to prod
- [ ] Change docker image used to a versioned one (later)

## User Data Store
- [ ] Update master branch
- [ ] Image on dockerhub?
- [ ] Configure new deployment pipelines
- [ ] Deploy to prod
- [ ] Change docker image used to a versioned one (later)

## Management Layer
- [ ] Update master branch
- [ ] Image on dockerhub?
- [ ] Configure new deployment pipelines
- [ ] Deploy to prod
- [ ] Change docker image used to a versioned one (later)

## Management Portal
- [ ] Update master branch
- [ ] Image on dockerhub?
- [ ] Configure new deployment pipelines
- [ ] Deploy to prod
- [ ] Change docker image used to a versioned one (later)
